### ISSUE TITLE
.Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by gyq-123** [theaidenlab/3d-dna#138]
Hi , I ran 3d-dna for a animal genome with the command:
sh 3d-dna/run-asm-pipeline.sh -r 2 -m diploid daimao.genome_2.rn.fasta merged_nodups.txt &>3d.log & 

I got error infomation as follows:

/home/u20199008/others/Gyq/solfware/3d-dna-201008/run-asm-pipeline.sh -r 2 -m diploid /home/u20199008/others/Gyq/daimao/hic/allhic/opt/references/daimao.genome_2.rn.fasta /home/u20199008/others/Gyq/daimao/hic/allhic/opt/aligned/merged_nodups.txt
version: 190716
 -r|--rounds flag was triggered, will run 2 round(s) of misjoin correction.
 -m|--mode flag was triggered. Running in diploid mode.
###############
Starting iterating scaffolding with editing:
...starting round 0 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: daimao.genome_2.rn.0.cprops
...Using merged_nodups file: daimao.genome_2.rn.mnd.0.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
...Starting iteration # 2
...Starting iteration # 3
...Starting iteration # 4
...Starting iteration # 5
...Starting iteration # 6
...Starting iteration # 7
...Starting iteration # 8
...Starting iteration # 9
...Starting iteration # 10
...Starting iteration # 11
...Starting iteration # 12
...Starting iteration # 13
...Starting iteration # 14
...Starting iteration # 15
...Starting iteration # 16
...Starting iteration # 17
...Starting iteration # 18
...Starting iteration # 19
...Starting iteration # 20
...Starting iteration # 21
...Starting iteration # 22
...Starting iteration # 23
...Starting iteration # 24
...Starting iteration # 25
...Starting iteration # 26
...Starting iteration # 27
...Starting iteration # 28
...Starting iteration # 29
...Starting iteration # 30
...Starting iteration # 31
:) DONE!
...visualizing round 0 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
Not including fragment map
Start preprocess
Writing header
Writing body
.Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:715)
	at java.base/java.lang.String.substring(String.java:1879)
	at java.base/java.lang.String.subSequence(String.java:1913)
	at com.google.common.base.Splitter$SplittingIterator.computeNext(Splitter.java:612)
	at com.google.common.base.Splitter$SplittingIterator.computeNext(Splitter.java:522)
	at com.google.common.base.AbstractIterator.tryToComputeNext(AbstractIterator.java:64)
	at com.google.common.base.AbstractIterator.hasNext(AbstractIterator.java:59)
	at com.google.common.base.Splitter.splitToList(Splitter.java:421)
	at juicebox.tools.utils.original.AsciiPairIterator.advance(AsciiPairIterator.java:93)
	at juicebox.tools.utils.original.AsciiPairIterator.next(AsciiPairIterator.java:194)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:387)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:283)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:108)
	at juicebox.tools.HiCTools.main(HiCTools.java:86)
...detecting misjoins in round 0 assembly:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 12500 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 62500 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 500 resolution
:) -b flag was triggered. Type of norm chosen for the contact matrix is KR.
...Dumping 12500 resolution matrix
HiC file version: 8
ERROR [2021-11-21 13:48:47,155]  [DatasetReaderV2.java:229] [main]  Error reading dataset
java.io.EOFException
	at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
	at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:435)
	at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:225)
	at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
	at juicebox.tools.HiCTools.main(HiCTools.java:85)
Could not read hic file: null
:( Juicebox dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
:) -w flag was triggered, performing cursory search for repeat at 12500 resolution
:) -t flag was triggered, flagging regions with coverage higher than 2
...Dumping 12500 resolution coverage track
HiC file version: 8
ERROR [2021-11-21 13:48:47,705]  [DatasetReaderV2.java:229] [main]  Error reading dataset
java.io.EOFException
	at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
	at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:435)
	at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:225)
	at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
	at juicebox.tools.HiCTools.main(HiCTools.java:85)
Could not read hic file: null
:( Juicebox coverage dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
mv: cannot stat 'depletion_score_wide.wig': No such file or directory
mv: cannot stat 'depletion_score_narrow.wig': No such file or directory
mv: cannot stat 'mismatch_wide.bed': No such file or directory
mv: cannot stat 'mismatch_narrow.bed': No such file or directory
mv: cannot stat 'coverage_wide.wig': No such file or directory
mv: cannot stat 'repeats_wide.bed': No such file or directory
awk: /home/u20199008/others/Gyq/solfware/3d-dna-201008/supp/plot_coverage.awk:9: fatal: cannot open file `coverage_wide.at.step.0.wig' for reading (No such file or directory)
cat: mismatch_narrow.at.step.0.bed: No such file or directory
cat: repeats_wide.at.step.0.bed: No such file or directory
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.1.*
...applying edits to cprops file
...applying edits to mnd file
...starting round 1 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: daimao.genome_2.rn.1.cprops
...Using merged_nodups file: daimao.genome_2.rn.mnd.1.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
...Starting iteration # 2
...Starting iteration # 3
...Starting iteration # 4
...Starting iteration # 5
...Starting iteration # 6
...Starting iteration # 7
...Starting iteration # 8
...Starting iteration # 9
...Starting iteration # 10
...Starting iteration # 11
...Starting iteration # 12
...Starting iteration # 13
...Starting iteration # 14
...Starting iteration # 15
...Starting iteration # 16
...Starting iteration # 17
...Starting iteration # 18
...Starting iteration # 19
...Starting iteration # 20
...Starting iteration # 21
...Starting iteration # 22
...Starting iteration # 23
...Starting iteration # 24
...Starting iteration # 25
...Starting iteration # 26
...Starting iteration # 27
...Starting iteration # 28
...Starting iteration # 29
...Starting iteration # 30
...Starting iteration # 31
:) DONE!
...visualizing round 1 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
Not including fragment map
Start preprocess
Writing header
Writing body
.Exception in thread "Timer-0" Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:715)
	at java.base/java.lang.String.substring(String.java:1879)
	at java.base/java.io.UnixFileSystem.parentOrNull(UnixFileSystem.java:233)
	at java.base/java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:166)
	at java.base/java.io.File.getCanonicalPath(File.java:626)
	at java.prefs/java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:921)
	at java.prefs/java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:748)
	at java.prefs/java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:843)
	at java.prefs/java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:483)
	at java.prefs/java.util.prefs.FileSystemPreferences$3.run(FileSystemPreferences.java:450)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.newTreeNode(HashMap.java:1807)
	at java.base/java.util.HashMap$TreeNode.putTreeVal(HashMap.java:2052)
	at java.base/java.util.HashMap.putVal(HashMap.java:633)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at juicebox.tools.utils.original.Preprocessor$BlockPP.incrementCount(Preprocessor.java:1065)
	at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.incrementCount(Preprocessor.java:1380)
	at juicebox.tools.utils.original.Preprocessor$MatrixPP.incrementCount(Preprocessor.java:1207)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:442)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:283)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:108)
	at juicebox.tools.HiCTools.main(HiCTools.java:86)
...detecting misjoins in round 1 assembly:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 12500 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 62500 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 500 resolution
:) -b flag was triggered. Type of norm chosen for the contact matrix is KR.
...Dumping 12500 resolution matrix
HiC file version: 8
ERROR [2021-11-21 16:03:13,576]  [DatasetReaderV2.java:229] [main]  Error reading dataset
java.io.EOFException
	at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
	at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:435)
	at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:225)
	at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
	at juicebox.tools.HiCTools.main(HiCTools.java:85)
Could not read hic file: null
:( Juicebox dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
:) -w flag was triggered, performing cursory search for repeat at 12500 resolution
:) -t flag was triggered, flagging regions with coverage higher than 2
...Dumping 12500 resolution coverage track
HiC file version: 8
ERROR [2021-11-21 16:03:14,114]  [DatasetReaderV2.java:229] [main]  Error reading dataset
java.io.EOFException
	at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
	at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:435)
	at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:225)
	at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
	at juicebox.tools.HiCTools.main(HiCTools.java:85)
Could not read hic file: null
:( Juicebox coverage dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
mv: cannot stat 'depletion_score_wide.wig': No such file or directory
mv: cannot stat 'depletion_score_narrow.wig': No such file or directory
mv: cannot stat 'mismatch_wide.bed': No such file or directory
mv: cannot stat 'mismatch_narrow.bed': No such file or directory
mv: cannot stat 'coverage_wide.wig': No such file or directory
mv: cannot stat 'repeats_wide.bed': No such file or directory
awk: /home/u20199008/others/Gyq/solfware/3d-dna-201008/supp/plot_coverage.awk:9: fatal: cannot open file `coverage_wide.at.step.1.wig' for reading (No such file or directory)
cat: mismatch_narrow.at.step.1.bed: No such file or directory
cat: repeats_wide.at.step.1.bed: No such file or directory
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.2.*
...applying edits to cprops file
...applying edits to mnd file
...starting round 2 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: daimao.genome_2.rn.2.cprops
...Using merged_nodups file: daimao.genome_2.rn.mnd.2.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
...Starting iteration # 2
...Starting iteration # 3
...Starting iteration # 4
...Starting iteration # 5
...Starting iteration # 6
...Starting iteration # 7
...Starting iteration # 8
...Starting iteration # 9
...Starting iteration # 10
...Starting iteration # 11
...Starting iteration # 12
...Starting iteration # 13
...Starting iteration # 14
...Starting iteration # 15
...Starting iteration # 16
...Starting iteration # 17
...Starting iteration # 18
...Starting iteration # 19
...Starting iteration # 20
...Starting iteration # 21
...Starting iteration # 22
...Starting iteration # 23
...Starting iteration # 24
...Starting iteration # 25
...Starting iteration # 26
...Starting iteration # 27
...Starting iteration # 28
...Starting iteration # 29
...Starting iteration # 30
...Starting iteration # 31
:) DONE!
...visualizing round 2 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
Not including fragment map
Start preprocess
Writing header
Writing body
.
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Timer-0"
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
###############
Starting polish:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, performing polishing taking into account signal with minimum 1 mapping quality
...-j flag was triggered, will use Juicebox map daimao.genome_2.rn.resolved.hic
...-a flag was triggered, will use scaffold annotation file daimao.genome_2.rn.resolved_asm.scaffold_track.txt
...-b flag was triggered, will use superscaffold annotation file daimao.genome_2.rn.resolved_asm.superscaf_track.txt
...-s flag was triggered, will ignore all scaffolds shorter than 1000000 for polishing
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 50000 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 1500000 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 500 resolution
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 50000 resolution
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -d flag was triggered, depletion score will be averaged across a region bounded by 1500000 superdiagonal
:) -n flag was triggered, performing mismatch region thinning at 500 resolution
...Dumping 50000 resolution matrix
HiC file version: 8
ERROR [2021-11-21 19:59:31,118]  [DatasetReaderV2.java:229] [main]  Error reading dataset
java.io.EOFException
	at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
	at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:435)
	at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:225)
	at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
	at juicebox.tools.HiCTools.main(HiCTools.java:85)
Could not read hic file: null
:( Juicebox dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
mv: cannot stat 'depletion_score_wide.wig': No such file or directory
mv: cannot stat 'depletion_score_narrow.wig': No such file or directory
mv: cannot stat 'mismatch_wide.bed': No such file or directory
mv: cannot stat 'mismatch_narrow.bed': No such file or directory
awk: /home/u20199008/others/Gyq/solfware/3d-dna-201008/edit/overlay-edits.awk:37: fatal: cannot open file `daimao.genome_2.rn.resolved.polish.mismatch_narrow.bed' for reading (No such file or directory)
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.polish.*
...applying edits to cprops file
...applying edits to mnd file
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
:) -s flag was triggered, starting calculations with 1000000 threshold starting contig/scaffold size
...Using cprops file: daimao.genome_2.rn.resolved.polish.cprops
...Using merged_nodups file: daimao.genome_2.rn.resolved.polish.mnd.txt
...Explicit scaffold set has been listed as input. Using set as a first iteration.
...Starting iteration # 1
:) DONE!
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
:) -s flag was triggered, starting calculations with 1000000 threshold starting contig/scaffold size
...Using cprops file: daimao.genome_2.rn.resolved.polish.cprops
...Using merged_nodups file: daimao.genome_2.rn.resolved.polish.mnd.txt
...Explicit scaffold set has been listed as input. Using set as a first iteration.
...Starting iteration # 1
:) DONE!
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
Not including fragment map
Start preprocess
Writing header
Writing body
.Exception in thread "Timer-0" Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.ArrayList.grow(ArrayList.java:238)
	at java.base/java.util.ArrayList.grow(ArrayList.java:243)
	at java.base/java.util.ArrayList.add(ArrayList.java:486)
	at java.base/java.util.ArrayList.add(ArrayList.java:499)
	at com.google.common.base.Splitter.splitToList(Splitter.java:422)
	at juicebox.tools.utils.original.AsciiPairIterator.advance(AsciiPairIterator.java:93)
	at juicebox.tools.utils.original.AsciiPairIterator.next(AsciiPairIterator.java:194)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:387)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:283)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:108)
	at juicebox.tools.HiCTools.main(HiCTools.java:86)
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:715)
	at java.base/java.lang.String.substring(String.java:1879)
	at java.base/java.io.UnixFileSystem.parentOrNull(UnixFileSystem.java:233)
	at java.base/java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:166)
	at java.base/java.io.File.getCanonicalPath(File.java:626)
	at java.prefs/java.util.prefs.FileSystemPreferences.lockFile(FileSystemPreferences.java:921)
	at java.prefs/java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:748)
	at java.prefs/java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:843)
	at java.prefs/java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:483)
	at java.prefs/java.util.prefs.FileSystemPreferences$3.run(FileSystemPreferences.java:450)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
mv: cannot stat 'daimao.genome_2.rn.resolved.polish.mismatch_narrow.bed': No such file or directory

**Comment by dudcha** [comment]
Hello gyq-123,

The issue is exactly as you have identified it: there isn't enough memory to build the contact map. Make sure you allocate enough memory. By default, the java job to build the contact map is run with 50Gb (https://github.com/aidenlab/3d-dna/blob/master/visualize/juicebox_tools.sh). If you are working with a particularly large dataset/genome, you may need to increase the parameters in juicebox_tools.sh.

Best,
Olga

**Comment by gyq-123** [comment]
The problem has been solved, thank you very much
