### ISSUE TITLE
Syntax error - awk

### ISSUE THREAD

**Issue by ddelgadillod** [theaidenlab/3d-dna#147]
Hi

I tried to run 3d-dna/visualize/run-assembly-visualizer.sh script in order to generate.hic file, input files like .assembly an .pairs were generated following Method II here specified, after it is running, appear an awk syntax error:

`:) -p flag was triggered. Running with GNU Parallel support parameter set to false.
...Remapping contact data from the original contig set to assembly
...Building track files
awk: Software/3d-dna/lift/lift-input-annotations-to-asm-annotations.awk: line 108: regular expression compile failed (syntax error ^* or ^+)
^+
...Building the hic file
Not including fragment map
java.lang.ArithmeticException: / by zero
	at juicebox.tools.utils.original.ExpectedValueCalculation.<init>(ExpectedValueCalculation.java:130)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:247)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:108)
	at juicebox.tools.HiCTools.main(HiCTools.java:86)`

Does anyone have an idea how to solve this?

**Comment by dudcha** [comment]
3D-DNA does not take “pairs" as input. Please see Genome Assembly Cookbook for instructions on how to use the tools. -Olga

**Comment by ddelgadillod** [comment]
Hi 
 I used the following to convert pairs to link files:

`
## Convert .pair file to merged_nodups.txt formats
grep -v '#' aln.pairs | \
  awk '{if($6!="+") $6=16; else $6=0; if($7!="+") $7=16; else $7=0} \
  $2<=$4{print $6, $2, $3, 0, $7, $4, $5, 1, "1 - - 1  - - -" } \
  $4<$2{print $7, $4, $5, 0, $6, $2, $3, 1, "1 - - 1  - - -" }' > out.links.txt `

Is the last procedure correct?

**Comment by dudcha** [comment]
The pair file is not our file format, I do not know it’s structure and a such cannot help with the conversion. Please see the cookbook for instructions on how to prepare the input. Thanks, -Olga
