### ISSUE TITLE
Unknown error: ERROR [2023-11-15 12:16:26,414]  [DatasetReaderV2.java:229] [main]  Error reading dataset java.io.EOFException

### ISSUE THREAD

**Issue by SwenDiepstraten** [theaidenlab/3d-dna#175]
Hello, I am encountering the following error in the split step. I am running the entire pipeline with an .mnd file generated from the pore-c-snakemake pipeline. This is the error:
Starting split:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
...-q flag was triggered, will ignore all reads with mapping quality less then 1 for polishing
...-j flag was triggered, will use Juicebox map assembly_no_scaffold.polished.hic
...-a flag was triggered, will use scaffold annotation file assembly_no_scaffold.polished_asm.scaffold_track.txt
...-b flag was triggered, will use superscaffold annotation file assembly_no_scaffold.polished_asm.superscaf_track.txt
...-s flag was triggered, will ignore all scaffolds shorter than 100000 for polishing
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 50000 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 1500000 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 500 resolution
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 50000 resolution
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -d flag was triggered, depletion score will be averaged across a region bounded by 1500000 superdiagonal
:) -n flag was triggered, performing mismatch region thinning at 500 resolution
...Dumping 50000 resolution matrix
HiC file version: 8
ERROR [2023-11-15 12:16:26,414]  [DatasetReaderV2.java:229] [main]  Error reading dataset
java.io.EOFException
	at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
	at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:435)
	at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:225)
	at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
	at juicebox.tools.HiCTools.main(HiCTools.java:85)
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.split.*
...applying edits to cprops file
...applying edits to mnd file
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
Not including fragment map
Start preprocess
Writing header
Writing body
.

What is this error, and how can I solve this?

Thanks in advance!

**Comment by lscnsdad** [comment]
Hello, how to solve this problem？
