### ISSUE TITLE
ask forhelp ： error when run run-asm-pipeline.sh

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [theaidenlab/3d-dna#180]
hello friend
 I assembly the genome with juicer and 3d-dna, when run the command "run-asm-pipeline.sh -r 0 raw_scaffold_2.fasta ./aligned/merged_nodups.txt"
its error 
![image](https://github.com/aidenlab/3d-dna/assets/101324838/702d261d-59cc-4631-a42f-5e3f328ce40b)

**Comment by Jiangjiangzhang6** [comment]
version: 180922
 -r|--rounds flag was triggered, will run 0 round(s) of misjoin correction.
###############
Starting iterating scaffolding with editing:
...starting round 0 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: raw_scaffold_2.0.cprops
...Using merged_nodups file: raw_scaffold_2.mnd.0.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
...Starting iteration # 2
...Starting iteration # 3
...Starting iteration # 4
...Starting iteration # 5
...Starting iteration # 6
...Starting iteration # 7
...Starting iteration # 8
...Starting iteration # 9
...Starting iteration # 10
:) DONE!
...visualizing round 0 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
Not including fragment map
Start preprocess
Writing header
Writing body
.###############
Starting polish:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, performing polishing taking into account signal with minimum 1 mapping quality
...-j flag was triggered, will use Juicebox map raw_scaffold_2.resolved.hic
...-a flag was triggered, will use scaffold annotation file raw_scaffold_2.resolved_asm.scaffold_track.txt
...-b flag was triggered, will use superscaffold annotation file raw_scaffold_2.resolved_asm.superscaf_track.txt
...-s flag was triggered, will ignore all scaffolds shorter than 1000000 for polishing
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 50000 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 1500000 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 500 resolution
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 50000 resolution
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -d flag was triggered, depletion score will be averaged across a region bounded by 1500000 superdiagonal
:) -n flag was triggered, performing mismatch region thinning at 500 resolution
...Dumping 50000 resolution matrix
HiC file version: 8
ERROR [2024-02-21 23:00:24,820]  [DatasetReaderV2.java:229] [main]  Error reading dataset
java.io.EOFException
        at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
        at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:435)
        at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:225)
        at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
        at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
        at juicebox.tools.HiCTools.main(HiCTools.java:85)
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.polish.*
...applying edits to cprops file
...applying edits to mnd file
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
:) -s flag was triggered, starting calculations with 1000000 threshold starting contig/scaffold size
...Using cprops file: raw_scaffold_2.resolved.polish.cprops
...Using merged_nodups file: raw_scaffold_2.resolved.polish.mnd.txt
...Explicit scaffold set has been listed as input. Using set as a first iteration.
...Starting iteration # 1
:) DONE!
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
:) -s flag was triggered, starting calculations with 1000000 threshold starting contig/scaffold size
...Using cprops file: raw_scaffold_2.resolved.polish.cprops
...Using merged_nodups file: raw_scaffold_2.resolved.polish.mnd.txt
...Explicit scaffold set has been listed as input. Using set as a first iteration.
...Starting iteration # 1
:) DONE!
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
Not including fragment map
Start preprocess
Writing header
Writing body
.###############
Starting split:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
...-q flag was triggered, will ignore all reads with mapping quality less then 1 for polishing
...-j flag was triggered, will use Juicebox map raw_scaffold_2.polished.hic
...-a flag was triggered, will use scaffold annotation file raw_scaffold_2.polished_asm.scaffold_track.txt
...-b flag was triggered, will use superscaffold annotation file raw_scaffold_2.polished_asm.superscaf_track.txt
...-s flag was triggered, will ignore all scaffolds shorter than 100000 for polishing
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 50000 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 1500000 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 500 resolution
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 50000 resolution
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -d flag was triggered, depletion score will be averaged across a region bounded by 1500000 superdiagonal
:) -n flag was triggered, performing mismatch region thinning at 500 resolution
...Dumping 50000 resolution matrix
HiC file version: 8
ERROR [2024-02-22 05:19:39,071]  [DatasetReaderV2.java:229] [main]  Error reading dataset
java.io.EOFException
        at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
        at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:435)
        at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:225)
        at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
        at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
        at juicebox.tools.HiCTools.main(HiCTools.java:85)
...-p flag was triggered. Running with GNU Parallel support parameter set to true.
...-r flag was triggered, output will be labeled as *.split.*
...applying edits to cprops file
...applying edits to mnd file
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
Not including fragment map
Start preprocess
Writing header
Writing body
.###############
Starting sealing:
... -i flag was triggered, will attempt to place back only debris contigs/scaffolds and those less than 15000
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
Not including fragment map
Start preprocess
Writing header
Writing body
.###############
Finilizing output:
... -s flag was triggered, treating all contigs/scaffolds shorter than 15000 as unattempted.
... -l flag was triggered. Output will appear with headers of the form raw_scaffold_2_hic_scaffold_#.
... -g flag was triggered, making gap size between scaffolded draft sequences to be equal to 500.
Analyzing the merged assembly
...trimming N overhangs
...adding gaps


how to debug this, lookiing forward for you reply.

**Comment by Jiangjiangzhang6** [comment]
just the hic file was  too small size,  the fasta was 2.2gb and the hic file was just 373kb

**Comment by Djangodu** [comment]
> hello friend I assembly the genome with juicer and 3d-dna, when run the command "run-asm-pipeline.sh -r 0 raw_scaffold_2.fasta ./aligned/merged_nodups.txt" its error ![image](https://private-user-images.githubusercontent.com/101324838/307488709-702d261d-59cc-4631-a42f-5e3f328ce40b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzQzMTAsIm5iZiI6MTcxMTA3NDAxMCwicGF0aCI6Ii8xMDEzMjQ4MzgvMzA3NDg4NzA5LTcwMmQyNjFkLTU5Y2MtNDYzMS1hNDJmLTVlM2YzMjhjZTQwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwMjIwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmEyZGI4NDBkMWU2MTU1OWEyYTUwZGFjNThhOWE3YzdlNjVlMmU4NGM0MmExMGI2YzIwYjk3OWYyNGQ2OTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J1k7Fp3DZy890cKbkn9UZen2bJKoN2ULL3EVl_vbgl8)

hello, friend
I miss this same issue, how about you now? did you solve it?

**Comment by Jiangjiangzhang6** [comment]
> > hello friend I assembly the genome with juicer and 3d-dna, when run the command "run-asm-pipeline.sh -r 0 raw_scaffold_2.fasta ./aligned/merged_nodups.txt" its error ![image](https://private-user-images.githubusercontent.com/101324838/307488709-702d261d-59cc-4631-a42f-5e3f328ce40b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzQzMTAsIm5iZiI6MTcxMTA3NDAxMCwicGF0aCI6Ii8xMDEzMjQ4MzgvMzA3NDg4NzA5LTcwMmQyNjFkLTU5Y2MtNDYzMS1hNDJmLTVlM2YzMjhjZTQwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwMjIwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmEyZGI4NDBkMWU2MTU1OWEyYTUwZGFjNThhOWE3YzdlNjVlMmU4NGM0MmExMGI2YzIwYjk3OWYyNGQ2OTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J1k7Fp3DZy890cKbkn9UZen2bJKoN2ULL3EVl_vbgl8)
> 
> hello, friend I miss this same issue, how about you now? did you solve it?
hello ,you should check your  fasta, you could seqkit or other tools to check the , maybe your fasta with the information that not ATGC, like X, or space

**Comment by Djangodu** [comment]
> > > hello friend I assembly the genome with juicer and 3d-dna, when run the command "run-asm-pipeline.sh -r 0 raw_scaffold_2.fasta ./aligned/merged_nodups.txt" its error ![image](https://private-user-images.githubusercontent.com/101324838/307488709-702d261d-59cc-4631-a42f-5e3f328ce40b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzQzMTAsIm5iZiI6MTcxMTA3NDAxMCwicGF0aCI6Ii8xMDEzMjQ4MzgvMzA3NDg4NzA5LTcwMmQyNjFkLTU5Y2MtNDYzMS1hNDJmLTVlM2YzMjhjZTQwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwMjIwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmEyZGI4NDBkMWU2MTU1OWEyYTUwZGFjNThhOWE3YzdlNjVlMmU4NGM0MmExMGI2YzIwYjk3OWYyNGQ2OTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J1k7Fp3DZy890cKbkn9UZen2bJKoN2ULL3EVl_vbgl8)
> > 
> > 
> > hello, friend I miss this same issue, how about you now? did you solve it?
> > hello ,you should check your  fasta, you could seqkit or other tools to check the , maybe your fasta with the information that not ATGC, like X, or space

may add wechat friend for detail help? d735712137

**Comment by dudcha** [comment]
Hi all,

Please see this discussion over here: https://groups.google.com/g/3d-genomics/c/OoCwQdL6yX0

You can exit 3d-dna at the point which is causing the problem and see if running with an updated jar will help. If you confirm that this is it you can just replace the jar in the 3d-dna/visualize folder with the one that was updated to address a similar issue.

Best,
Olga

**Comment by lscnsdad** [comment]
hello, friend
I miss this same issue, how to solve this problem？
