### ISSUE TITLE
Error reading datasetnull

### ISSUE THREAD

**Issue by fisisi** [theaidenlab/3d-dna#188]
Hi,
I got this issue when I was running juicer. Is anyone meet this error before?

Error reading datasetnull
java.io.EOFException
        at htsjdk.tribble.util.LittleEndianInputStream.readFully(LittleEndianInputStream.java:138)
        at htsjdk.tribble.util.LittleEndianInputStream.readLong(LittleEndianInputStream.java:80)
        at htsjdk.tribble.util.LittleEndianInputStream.readDouble(LittleEndianInputStream.java:100)
        at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:470)
        at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:235)
        at juicebox.tools.utils.original.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:78)
        at juicebox.tools.clt.old.AddNorm.run(AddNorm.java:84)
        at juicebox.tools.HiCTools.main(HiCTools.java:96)

real    0m8.205s
user    0m1.196s
sys     0m0.421s
/apps/juicer/scripts/common/juicer_tools is post-processing Hi-C for Vpom
Data read from /01.asm/Hic/aligned/inter_30.hic.
Motifs read from /apps/juicer/references/motif

ARROWHEAD:

Picked up _JAVA_OPTIONS: -Xmx150000m -Xms150000m
Reading file: /01.asm/Hic/aligned/inter_30.hic
Error reading datasetnull
Could not read hic file: null
***! Problem while running Arrowhead
***! Error! Either inter.hic or inter_30.hic were not created
Either inter.hic or inter_30.hic were not created.  Check  for results

My script is follwing:
/apps/juicer/scripts/juicer.sh -g Vpom -z /Hic/reference/Vpom.asm.hic.p_ctg.fa -p /01.asm/Hic/Vpom.chrom.sizes -s none -d /01.asm/Hic -t 96

**Comment by mengying0714** [comment]
Have you solved this question? I have the same question.

**Comment by fisisi** [comment]
> Have you solved this question? I have the same question.

Try the follwing script:
juicer.sh -g genome -z /juicer/reference/genome.fa -d /juicer -p /juicer/sorted_size_file.txt -s none -t 10  -C 40000000 -D /apps/juicer/2.0/juicer/ -e
